import React, { useState } from 'react';
import { X, Code, Copy, Check, Download, ShieldCheck, Layers, FileCode, Search, CheckCircle2 } from 'lucide-react';
import { HmiDsl } from '../types';

interface DslViewerProps {
  isOpen: boolean;
  onClose: () => void;
  dsl?: HmiDsl;
}

export const DslViewer: React.FC<DslViewerProps> = ({ isOpen, onClose, dsl }) => {
  const [copied, setCopied] = useState(false);
  const [searchFilter, setSearchFilter] = useState('');

  if (!isOpen) return null;

  const rawJsonStr = JSON.stringify(dsl || {}, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(rawJsonStr);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([rawJsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `hmi_spec_${dsl?.screen || 'runtime'}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Render line with JSX formatting
  const renderFormattedLine = (line: string) => {
    // Regex tokenizer for JSON
    const tokens = line.split(/("[\s\S]*?"|:\s*|\[|\]|\{|\}|,|\btrue\b|\bfalse\b|\bnull\b|-?\d+(?:\.\d+)?)/g);

    return tokens.map((token, i) => {
      if (!token) return null;

      if (token.startsWith('"') && token.endsWith('"')) {
        // Check if key or string value
        const isKey = line.indexOf(token + ':') !== -1 || line.indexOf(token + ' :') !== -1;
        return (
          <span key={i} style={{ color: isKey ? '#60a5fa' : '#34d399', fontWeight: isKey ? 'bold' : 'normal' }}>
            {token}
          </span>
        );
      } else if (token === 'true' || token === 'false') {
        return <span key={i} style={{ color: '#a78bfa', fontWeight: 'bold' }}>{token}</span>;
      } else if (token === 'null') {
        return <span key={i} style={{ color: '#f87171', fontWeight: 'bold' }}>{token}</span>;
      } else if (!isNaN(Number(token)) && token.trim() !== '') {
        return <span key={i} style={{ color: '#f59e0b', fontWeight: 'bold' }}>{token}</span>;
      } else if (token.includes(':')) {
        return <span key={i} style={{ color: '#94a3b8' }}>{token}</span>;
      } else {
        return <span key={i} style={{ color: '#e2e8f0' }}>{token}</span>;
      }
    });
  };

  const lines = rawJsonStr.split('\n');
  const widgets = dsl?.widgets || [];

  return (
    <div style={{ position: 'fixed', inset: 0, zIndex: 100, backgroundColor: 'rgba(2, 6, 23, 0.9)', backdropFilter: 'blur(6px)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '16px' }}>
      <div style={{ backgroundColor: '#0b0f17', border: '1px solid #1e293b', borderRadius: '12px', width: '100%', maxWidth: '1280px', height: '90vh', display: 'flex', flexDirection: 'column', boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.8)', overflow: 'hidden' }}>
        
        {/* Header */}
        <div style={{ padding: '16px 24px', borderBottom: '1px solid #1e293b', backgroundColor: '#121721', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Code size={20} style={{ color: '#00e676' }} />
              <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '1.25rem', fontWeight: 700, color: '#ffffff', margin: 0 }}>
                APPROVED HMI SPECIFICATION (JSON DSL)
              </h2>
              <span style={{ backgroundColor: '#052e16', border: '1px solid #14532d', color: '#00e676', fontSize: '10px', fontFamily: 'var(--font-mono)', fontWeight: 'bold', padding: '2px 8px', borderRadius: '4px', display: 'flex', alignItems: 'center', gap: '4px' }}>
                <ShieldCheck size={12} /> SAFETY GATE APPROVED ✓
              </span>
            </div>
            <p style={{ fontSize: '12px', color: '#94a3b8', fontFamily: 'var(--font-mono)', margin: '4px 0 0 0' }}>
              "Declarative HMI specification generated by AI Screen Planner & verified by Safety Gate"
            </p>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <button
              onClick={handleCopy}
              className="btn-secondary"
              style={{ border: '1px solid #059669', backgroundColor: '#064e3b', color: '#a7f3d0' }}
            >
              {copied ? <Check size={14} style={{ color: '#00e676' }} /> : <Copy size={14} />}
              <span>{copied ? 'COPIED' : 'COPY JSON'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="btn-secondary"
              style={{ border: '1px solid #2563eb', backgroundColor: '#172554', color: '#60a5fa' }}
            >
              <Download size={14} />
              <span>DOWNLOAD SPEC</span>
            </button>

            <button
              onClick={onClose}
              style={{ backgroundColor: '#1e293b', border: '1px solid #334155', color: '#cbd5e1', padding: '6px', borderRadius: '6px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Main Body: 2 Columns */}
        <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
          
          {/* Left Column: Screen Overview & Widget Breakdown (40%) */}
          <div style={{ width: '420px', borderRight: '1px solid #1e293b', backgroundColor: '#121721', padding: '20px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '20px' }}>
            
            {/* Screen Metadata Card */}
            <div style={{ backgroundColor: '#06090e', border: '1px solid #1e293b', borderRadius: '8px', padding: '16px' }}>
              <div style={{ fontSize: '10px', fontFamily: 'var(--font-mono)', color: '#60a5fa', textTransform: 'uppercase', fontWeight: 'bold', marginBottom: '8px' }}>
                SPECIFICATION SUMMARY
              </div>
              <div style={{ fontSize: '1.1rem', fontWeight: 700, color: '#ffffff', fontFamily: 'var(--font-heading)', marginBottom: '8px' }}>
                {dsl?.title || 'Packaging Line 1 Screen'}
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', fontSize: '11px', fontFamily: 'var(--font-mono)', color: '#94a3b8' }}>
                <div>Screen ID: <span style={{ color: '#00e676', fontWeight: 'bold' }}>{dsl?.screen || 'runtime_screen'}</span></div>
                <div>Layout Engine: <span style={{ color: '#f59e0b' }}>{dsl?.layout || 'responsive'}</span></div>
                <div>Total Widgets: <span style={{ color: '#60a5fa', fontWeight: 'bold' }}>{widgets.length}</span></div>
              </div>
            </div>

            {/* Safety Gate Verification Certificate Card */}
            <div style={{ backgroundColor: '#06090e', border: '1px solid #14532d', borderRadius: '8px', padding: '16px' }}>
              <div style={{ fontSize: '11px', fontFamily: 'var(--font-heading)', fontWeight: 'bold', color: '#00e676', display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '10px' }}>
                <ShieldCheck size={16} /> DETERMINISTIC VALIDATION CERTIFICATE
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', fontSize: '11px', fontFamily: 'var(--font-mono)' }}>
                <div style={{ color: '#34d399', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <CheckCircle2 size={13} style={{ color: '#00e676' }} /> Tag Existence Gate: <span style={{ color: '#ffffff', fontWeight: 'bold' }}>PASS</span>
                </div>
                <div style={{ color: '#34d399', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <CheckCircle2 size={13} style={{ color: '#00e676' }} /> Read-Only Permission Gate: <span style={{ color: '#ffffff', fontWeight: 'bold' }}>PASS</span>
                </div>
                <div style={{ color: '#34d399', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <CheckCircle2 size={13} style={{ color: '#00e676' }} /> Operator Interlock Gate: <span style={{ color: '#ffffff', fontWeight: 'bold' }}>PASS</span>
                </div>
                <div style={{ color: '#34d399', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <CheckCircle2 size={13} style={{ color: '#00e676' }} /> DSL Schema Compliance: <span style={{ color: '#ffffff', fontWeight: 'bold' }}>PASS</span>
                </div>
                <div style={{ color: '#34d399', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <CheckCircle2 size={13} style={{ color: '#00e676' }} /> Execution Safety Check: <span style={{ color: '#ffffff', fontWeight: 'bold' }}>PASS</span>
                </div>
              </div>
            </div>

            {/* Widget Breakdown List */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              <div style={{ fontSize: '11px', fontFamily: 'var(--font-heading)', fontWeight: 'bold', color: '#94a3b8', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <Layers size={14} style={{ color: '#60a5fa' }} /> COMPOSED HMI WIDGETS ({widgets.length})
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {widgets.map((w, idx) => (
                  <div key={idx} style={{ backgroundColor: '#06090e', border: '1px solid #1e293b', padding: '10px 12px', borderRadius: '6px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '4px' }}>
                      <span style={{ fontSize: '12px', fontWeight: 600, color: '#f8fafc', fontFamily: 'var(--font-heading)' }}>
                        {w.title || w.tag || w.type}
                      </span>
                      <span style={{ fontSize: '9px', padding: '2px 6px', borderRadius: '3px', backgroundColor: '#1e3a8a', color: '#60a5fa', fontFamily: 'var(--font-mono)', fontWeight: 'bold' }}>
                        {w.type.toUpperCase()}
                      </span>
                    </div>
                    <div style={{ fontSize: '10px', color: '#94a3b8', fontFamily: 'var(--font-mono)' }}>
                      Target Tag: <span style={{ color: '#00e676' }}>{w.tag || 'N/A'}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* Right Column: Formatted Syntax-Highlighted JSON Viewer (60%) */}
          <div style={{ flex: 1, backgroundColor: '#06090e', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
            
            {/* JSON Code Window Header */}
            <div style={{ padding: '10px 16px', borderBottom: '1px solid #1e293b', backgroundColor: '#121721', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '11px', fontFamily: 'var(--font-mono)', color: '#94a3b8' }}>
                <FileCode size={14} style={{ color: '#00e676' }} />
                <span>hmi_dsl_spec.json</span>
                <span style={{ color: '#475569' }}>|</span>
                <span>{lines.length} lines</span>
              </div>

              {/* Quick Search inside JSON */}
              <div style={{ position: 'relative', width: '220px' }}>
                <Search size={12} style={{ position: 'absolute', left: '8px', top: '50%', transform: 'translateY(-50%)', color: '#64748b' }} />
                <input
                  type="text"
                  placeholder="Filter JSON..."
                  value={searchFilter}
                  onChange={(e) => setSearchFilter(e.target.value)}
                  style={{
                    width: '100%',
                    padding: '4px 8px 4px 26px',
                    backgroundColor: '#06090e',
                    border: '1px solid #1e293b',
                    borderRadius: '4px',
                    color: '#ffffff',
                    fontSize: '11px',
                    fontFamily: 'var(--font-mono)'
                  }}
                />
              </div>
            </div>

            {/* Syntax Highlighted JSON Content */}
            <div style={{ flex: 1, padding: '16px', overflowY: 'auto', fontFamily: 'var(--font-mono)', fontSize: '12px' }}>
              {lines.map((line, idx) => {
                if (searchFilter && !line.toLowerCase().includes(searchFilter.toLowerCase())) {
                  return null;
                }
                return (
                  <div key={idx} style={{ display: 'flex', lineHeight: '1.6' }}>
                    <span style={{ width: '36px', color: '#475569', textAlign: 'right', paddingRight: '12px', userSelect: 'none', flexShrink: 0 }}>
                      {idx + 1}
                    </span>
                    <div style={{ whiteSpace: 'pre' }}>
                      {renderFormattedLine(line)}
                    </div>
                  </div>
                );
              })}
            </div>

          </div>

        </div>

      </div>
    </div>
  );
};
